defaults: &defaults
  app_name: "Rails開發用"
  domain: "http://groupme.dev"
  facebook_app_id: 
  facebook_secret: 
  hipchat_token: 
  hipchat_room_name: 
  admin_emails: 
    - ""
  google_analytics_key: ""
  default_logo_url: "/logo.png"
  email_sender: "postmaster@ritw.mailgun.org"
  
defaults: &defaults2
  app_name: "Rails上線用"
  domain: "https://david-rails101.herokuapp.com"
  facebook_app_id: 
  facebook_secret: 
  hipchat_token: 
  hipchat_room_name: 
  admin_emails: 
    - ""
  google_analytics_key: ""
  default_logo_url: "/logo.png"
  email_sender: "postmaster@ritw.mailgun.org"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults2

